name: orders_app
description: Dart web project for the Orders exam (pure Dart, no Flutter)
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.10.1
  build_web_compilers: ^4.3.2
